<?php /** @var bool $status
 * @var \CustomUser\Entity\User $user */
$user = $this->zfcUserIdentity(); ?>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= sprintf($this->translate('Change Password for %s'), $user->getFirstName() . ' ' . $user->getLastName()); ?></h3>
                </div>
                <div class="panel-body">
                    <?php if ($status === true) { ?>
                        <div class="alert alert-success"><?= $this->translate('Password changed successfully.'); ?></div>
                    <?php } elseif ($status === false) { ?>
                        <div class="alert alert-error"><?= $this->translate('Unable to update your password. Please try again.'); ?></div>
                    <?php }
                    /** @var \Zend\Form\Form $form */
                    $form = $this->changePasswordForm;
                    $form->prepare();
                    $form->setAttribute('action', $this->url('zfcuser/changepassword'));
                    $form->setAttribute('method', 'post');
                    $form->setAttribute('autocomplete', 'off'); ?>

                    <?php echo $this->partial('_form.phtml', ['form' => $form]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
