<?php $current = $this->url(); ?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home'); ?>">
                <img src="<?= $this->basePath('assets/client/images/zf-logo-mark.svg'); ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION; ?>"/>&nbsp;Skeleton Application
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li <?php if ($current === '/') { echo 'class="active"'; } ?>><a href="<?= $this->url('home'); ?>">Home</a></li>
                <?php if($this->zfcUserIdentity()) { ?>
                    <li <?php if ($current === '/user') { echo 'class="active"'; } ?>><a href="<?= $this->url('scn-social-auth-user'); ?>">Profile</a></li>
                    <li><a href="<?= $this->url('scn-social-auth-user/logout'); ?>">Sign Out</a></li>
                <?php } else { ?>
                    <li <?php if ($current === '/user/login') { echo 'class="active"'; } ?>><a href="<?= $this->url('scn-social-auth-user/login'); ?>"><?= $this->translate('Sign In'); ?></a></li>
                    <li <?php if ($current === '/user/register') { echo 'class="active"'; } ?>><a href="<?= $this->url('scn-social-auth-user/register'); ?>"><?= $this->translate('Register'); ?></a></li>
                <?php } ?>
            </ul>
        </div>
    </div>
</nav>